model:
  class_path: lightning_models.lightning_diffusion_mlp.LightningDiffusionClassifier
  init_args:
    num_classes: 13
    embedding_dim: 668
    loss_weighted: True
    loss_pos_weight: 12
    alpha: 0.05
    dropout_rate: 0.2
    lr: 1e-4
    residual: True
    activation_fn: torch.nn.GELU
    size: 'dino_small'
    results_path: "./results_test.csv"

data:
  class_path: datamodules.bbbc021_data_module.BBBC021DataModule
  init_args:
    data_dir: '/net/pr2/projects/plgrid/plggicv/jk/datasets/BBBC021'
    mask_uncertain: True

trainer:
  max_epochs: 40
  check_val_every_n_epoch: 5
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "hcs-dfc-diffusion-final-fix-bbbc-cp"
      name: "bbbc-cp-xsm-diffusion"
      tags: [ "diffusion", "bbbc", "cp" ]
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: './checkpoints/bbbc_cp/diffusion/lg'
        filename: 'epoch={epoch}-val_loss={val_loss:.2f}'
        monitor: 'val_loss'
        mode: 'min'
        save_top_k: 3
        every_n_epochs: 90
        save_last: true