model:
  class_path: lightning_models.lightning_diffusion_mlp.LightningDiffusionClassifier
  init_args:
    num_classes: 30
    embedding_dim: 512
    loss_weighted: False
    loss_pos_weight: 5.21
    alpha: 0.05
    dropout_rate: 0.2
    lr: 1e-4
    size: 'dino_small'
    residual: True
    activation_fn: torch.nn.ReLU
    results_path: "./results/bray_cloome/diffusion/results_0.05csv"

data:
  class_path: datamodules.image_feature_data_module.ImageFeatureDataModule
  init_args:
    split_col: 'hier_split_0'
    data_csv_path: '/net/pr2/projects/plgrid/plggicv/jk/datasets/bray_cloome/bbbc_cloome_dataset.csv'
    mask_uncertain: True # Update data dir to match your environment
    validation_split_val: "cal"

trainer:
  max_epochs: 60
  check_val_every_n_epoch: 5
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "hcs-dfc-diffusion-final-bray-cloome"
      name: "bray-cloome-xsm-diffusion"
      tags: [ "diffusion", "bray", "cloome" ]
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: './checkpoints/bray_cloome/diffusion/xsm'
        filename: 'epoch={epoch}-val_loss={validation_loss:.2f}'
        monitor: 'validation_loss'
        mode: 'min'
        save_top_k: 6
        every_n_epochs: 70
        save_last: true


