import torch
import torchvision
from torch.utils.data import DataLoader

from datamodules.base_data_module import BaseDataModule
from datasets.two_digit_mnist_dataset import TwoDigitMNISTDataset


class TwoDigitMNISTDataModule(BaseDataModule):
    def __init__(
        self,
        transform=None,
        batch_size: int = 128,
        data_dir: str = "_data/dual_mnist/raw",
        noise_std: float = 0.3,
        use_masked_labels: bool = False,
        mask_symbol: float = -1.0,
    ):
        """
        Parameters
        ----------
        batch_size : int
            Number of samples per mini-batch.
        data_dir : str
            Root directory that contains the split CSVs (train/val/test.csv)
            and the ``images/`` sub-directory.
        noise_std : float
            Standard deviation of Gaussian noise added to images.
        use_masked_labels : bool
            When ``True``, the dataset returns masked label vectors and a
            binary mask tensor derived from them (``1`` = observed,
            ``0`` = uncertain/masked).  Requires the CSV to contain
            ``masked_digit_*`` columns (i.e. generated by
            ``generate_occluded_masked_2_digit_mnist.py``).
            Falls back silently to clean labels / all-ones mask when the
            masked columns are absent from the CSV.
        mask_symbol : float
            Sentinel value that marks unknown label positions in the
            ``masked_digit_*`` columns (must match the value used during
            dataset generation, default ``-1.0``).
        """
        super().__init__()
        self.batch_size = batch_size
        self.data_dir = data_dir
        self.seed = 42
        self.noise_std = noise_std
        self.use_masked_labels = use_masked_labels
        self.mask_symbol = mask_symbol
        self.transform = transform

        # Training transform: convert image to tensor and add Gaussian noise
        transforms = []
        if self.transform is not None:
            transforms.append(self.transform)
        transforms.extend(
            [
                torchvision.transforms.ToTensor(),
                torchvision.transforms.Lambda(
                    lambda x: x + torch.randn_like(x) * self.noise_std
                ),
            ]
        )
        self.train_transform = torchvision.transforms.Compose(transforms)

        # Validation / test transform: same noise level for consistency
        self.test_val_transform = torchvision.transforms.Compose(transforms)

    def _make_dataset(self, split: str, transform) -> TwoDigitMNISTDataset:
        return TwoDigitMNISTDataset(
            image_dir=self.data_dir,
            csv_file=f"{self.data_dir}/{split}.csv",
            transform=transform,
            use_masked_labels=self.use_masked_labels,
            mask_symbol=self.mask_symbol,
        )

    def setup(self, stage: str) -> None:
        if stage == "fit":
            self.train_dataset = self._make_dataset("train", self.train_transform)
            self.val_dataset = self._make_dataset("val", self.test_val_transform)

        if stage == "test":
            self.test_dataset = self._make_dataset("test", self.test_val_transform)

        if stage == "validate":
            self.val_dataset = self._make_dataset("val", self.test_val_transform)

    def train_dataloader(self) -> DataLoader:
        return DataLoader(self.train_dataset, batch_size=self.batch_size, shuffle=True)

    def val_dataloader(self) -> DataLoader:
        return DataLoader(self.val_dataset, batch_size=self.batch_size, shuffle=False)

    def test_dataloader(self) -> DataLoader:
        return DataLoader(self.test_dataset, batch_size=self.batch_size, shuffle=False)
